name: Test action

on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: test-branch
          suffix: -done

  create-branch:
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes'