name: Restrict merge from develop to main

on:
  pull_request:
    branches: [ main ]

jobs:
  check-compare-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check compare branch
        run: |
          # PR 소스 브랜치가 develop일 경우, 실패 그 외의 브랜치면 통과
          if [[ "$GITHUB_HEAD_REF" == 'develop' ]]; then exit 1; else exit 0; fi;